-- MySQL Script generated by MySQL Workbench
-- Mon Sep  2 16:46:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tourism
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tourism
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tourism` DEFAULT CHARACTER SET utf8mb3 ;
USE `tourism` ;

-- -----------------------------------------------------
-- Table `tourism`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`employees` (
  `idEmployees` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idEmployees`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tourism`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`services` (
  `idServices` INT NOT NULL,
  `ServiceName` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idServices`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tourism`.`usersinvoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`usersinvoice` (
  `idServices` INT NOT NULL,
  `InvoiceName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idServices`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tourism`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `UserSurname` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idUsers`),
  CONSTRAINT `UserInvoiceId`
    FOREIGN KEY (`idUsers`)
    REFERENCES `tourism`.`usersinvoice` (`idServices`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tourism`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`orders` (
  `idOrders` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idOrders`),
  CONSTRAINT `EmployeeID`
    FOREIGN KEY (`idOrders`)
    REFERENCES `tourism`.`employees` (`idEmployees`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ServiceID`
    FOREIGN KEY (`idOrders`)
    REFERENCES `tourism`.`services` (`idServices`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `UserID`
    FOREIGN KEY (`idOrders`)
    REFERENCES `tourism`.`users` (`idUsers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
